apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: forsvc
      port: 21
      targetPort: 21
    - protocol: TCP
      name: passport
      port: 10100
      targetPort: 10100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-dpl
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps_image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 10100